Add controllers
Difirton/java-shareit pull request #1
Opened 2022-10-18 21:47 UTC by Difirton

Тут чуть-чуть больше чем просто контроллеры=)
В userService есть ветвление, которое проверяет: есть ли юзер в БД перед сохранением, это временная история. В ТЗ спринта 15 она будет удалена. NamedEntityGraph написал для 15 спринта, я просто тесты прогонял для него, было интересно.

2022-10-19 16:01 UTC, Frilock requested changes
Добрый день, пара комментариев оставил, в целом такие, больше на обсуждение.

2022-10-19 16:01 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repository/Booking.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "bookings_seq")
А почему такая стратегия странная?  Помоему стандартная     @GeneratedValue(strategy = GenerationType.IDENTITY), тогда не надо сиквенс генерировать

2022-10-19 16:01 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repository/Booking.java
> +    @Column(name = "id", nullable = false)
Для Id можно Column не ставить

2022-10-19 16:01 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repository/Booking.java
> +    LocalDateTime start;
Интересный момент, а почему вы модификаторы не проставили? Явно же не просто так

2022-10-19 16:01 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getStart().isBefore(booking.getFinish())) {
Не посмотрел booking.getStart() не вернет null случайно

2022-10-19 16:01 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/Item.java
> +    private String name;
Вообще в плане хорошей практики, когда в скриптах генерацию таблиц будете делать, указывайте размер, а тот размер указывать в Column

2022-10-19 16:01 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemCustomRepositoryImpl.java
> +        if (pattern.equals("")) {
А pattern null прийти не сможет?

2022-10-19 18:31 UTC, Difirton commented on src/main/java/ru/practicum/shareit/booking/repository/Booking.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "bookings_seq")
Если честно, не помню где, но читал, что PostgreSQL не рекомендована или не поддерживает Identity. А поскольку у нас в pom.xml добавлены драйвера от PostgreSql + в пропертис тоже настройки от PostgreSQL + у нас дробление проекта по сервисам, я подумал, что мы будем пилить монолит на микросервисы и поднимать их в Docker-контейнерах, а качестве БД будет использована PostgreSQL. Поэтому решил сразу использовать Sequence.

2022-10-19 18:33 UTC, Difirton commented on src/main/java/ru/practicum/shareit/booking/repository/Booking.java
> +    @Column(name = "id", nullable = false)
Удалю. Я на самом деле обычно не ставлю, это мне Idea нагенерила, я подумал это бест практисис=)

2022-10-19 19:02 UTC, Difirton commented on src/main/java/ru/practicum/shareit/booking/repository/Booking.java
> +    LocalDateTime start;
Случайно, мой косяк, исправлю. Это последствия оптимизации написания кода, когда начал писать с контроллеров, а потом в сервисы, а потом сгенерил в идее, потому что уже понял, что хочу видеть и пока писал Builder, не заметил, что вверху поля не private.

2022-10-19 19:04 UTC, Difirton commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getStart().isBefore(booking.getFinish())) {
Забываю о том, чтобы подумать в сторону возможного null, поставлю себе пометку, чтобы каждый раз думать в этом направлении.

2022-10-19 19:05 UTC, Difirton commented on src/main/java/ru/practicum/shareit/item/repository/Item.java
> +    private String name;
Спасибо, исправил.

2022-10-19 19:06 UTC, Difirton commented on src/main/java/ru/practicum/shareit/item/repository/ItemCustomRepositoryImpl.java
> +        if (pattern.equals("")) {
Вообще нет, контроллер завернет с ошибкой 400, но сейчас подумал, что репозиторий может использоваться другими сервисами, добавил проверку.

2022-10-20 16:24 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repository/Booking.java
> +    @Column(name = "id", nullable = false)
Ставить Column да, но не над id =)

2022-10-20 16:38 UTC, Frilock approved these changes
Добрый день, принял, но пару комментариев оставил

2022-10-20 16:38 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemCustomRepositoryImpl.java
> +        if (pattern == null || pattern.equals("")) {
Когда строку проверяете есть прекрасная штука от StringUtils.isNotBlank/isBlank и т.д.

2022-10-20 16:38 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/repository/User.java
> +@ToString(exclude = {"items", "itemRequests", "bookings"})
Когда полей мало, то можно вместо exclude использовать of

2022-10-20 16:38 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repository/Booking.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "bookings_seq")
Странно, не слышал о такой проблеме для постгреса, хотя у нас и оракл на проекте сейчас. Не берусь утверждать в общем.

2022-10-20 17:01 UTC, Difirton commented on src/main/java/ru/practicum/shareit/booking/repository/Booking.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "bookings_seq")
Поищу в книге про JPA и Hibernate, вроде, как раз там и видел. Если буду не прав, отпишусь.

2022-10-20 17:02 UTC, Difirton commented on src/main/java/ru/practicum/shareit/item/repository/ItemCustomRepositoryImpl.java
> +        if (pattern == null || pattern.equals("")) {
Блин, пора привыкнуть, что есть утилитный класс для стандартных объектов на все случаи жизни, спасибо=)

2022-10-20 17:13 UTC, Difirton commented on src/main/java/ru/practicum/shareit/user/repository/User.java
> +@ToString(exclude = {"items", "itemRequests", "bookings"})
Да, начиналось все с 1 поля, а потом развелось много=)

2022-10-20 17:17 UTC, merged