Add docker
Difirton/java-shareit pull request #4
Opened 2022-12-03 15:27 UTC by Difirton

2022-12-04 11:54 UTC, Frilock requested changes
Добрый день, по работе, из pom файла должна быть удалена зависимость на валидацию, это прям жесткое требование.
Пропали модификаторы в контроллерах которые вы перенесли.
По поводу тестов, те тесты которые вы удаляете из server, должны быть перенесены в gateway.

2022-12-04 11:54 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        return bookingClient.findAllByBookerId(userId, this.checkState(stateName), from.orElse(0),
0 и 10 по идее нужно в константы вынести, либо через аннотации на параметры min и max

2022-12-04 11:54 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +            if (parameters != null) {
Данную конструкцию можно заменить на тернарное выражение, будет выглядеть компактнее.

2022-12-04 11:54 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/item/ItemClient.java
> +
Лишняя пустая строчка

2022-12-04 11:54 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    ResponseEntity<Object> getItemById(@Parameter(description = "Item ID") @PathVariable("id") Long id,
А куда модификатор подевался

2022-12-04 11:54 UTC, Frilock commented on server/pom.xml
> +		<dependency>
Данной зависимости не должно быть в этом pom файле. В этом вся и задача по идее

2022-12-04 19:24 UTC, Difirton commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        return bookingClient.findAllByBookerId(userId, this.checkState(stateName), from.orElse(0),
Ну да, кстати, нужно было это сделать изначально.

2022-12-04 19:25 UTC, Difirton commented on gateway/src/main/java/ru/practicum/shareit/item/ItemClient.java
> +
Исправил

2022-12-04 19:25 UTC, Difirton commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +            if (parameters != null) {
Хаха, это то, что нам дал практикум по дефолту я даже сюда не лез=))

2022-12-04 19:41 UTC, Difirton commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    ResponseEntity<Object> getItemById(@Parameter(description = "Item ID") @PathVariable("id") Long id,
А вот это, кстати интересный вопрос. Тут любопытно узнать Ваше мнение. Я в контроллерах намеренно использовал package-private. Так как не планирую, что контроллеры где-то в проекте будут использованы. Эту идею увидел в тьюбе в одном из видосов про ошибки в коде, что не соблюдается инкапслуяция, т.к. контроллеры не предназначены для их вызова из вне.

2022-12-04 21:34 UTC, Difirton commented on server/pom.xml
> +		<dependency>
Ок. Убрал. Кстати у меня как во фразе при "съемках фильма ни одно животное не пострадало", так и у меня ни почти ни один тест не сломался)), так что все остались не тронутыми. Пришлось еще парочку добавить, чтобы покрытие опять стало больше 90% строк, т.к. я удалил свагеровские аннотации из сервера.

2022-12-05 06:23 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    ResponseEntity<Object> getItemById(@Parameter(description = "Item ID") @PathVariable("id") Long id,
Кстати ну вот в моей практике приходилось из одного контроллера другой вызывать =) Кейс был вероятно не очень хороший, но приходилось, поскольку именно на вызов контроллера срабатывали различные надстройки, поэтому вызовом сервиса было не обойтись. Поэтому по тупому инжектил контроллер и его вызывал. 
А так просто как то "исторически" сложилось, что ставлю в контроллерах public модификаторы, хотя думаю, что и ты отчасти прав

2022-12-05 06:32 UTC, Frilock requested changes
Доброе утро, пара мелких комментариев и принимаю работу.

2022-12-05 06:32 UTC, Frilock commented on server/pom.xml
> +			<version>42.3.8</version>
А чего версию в properties не вынес?)
Кстати, я обычно этот коммент на дипломе пишу, но:
Общий комментарий по pom файлам. Смотрите, у Вас многомодульный проект, сейчас он состоит из 2х модулей, но возможно их будет больше. Так вот, хочется чтобы в приложении была одна точка добавления зависимостей. Такой обычно делают корневой pom файл. Там нужно сделать блок dependencyManager и добавлять те библиотеки которых нет в parent, а затем уже в других pom файлах подключать, но уже без указания версии. Кроме того, версии этих библиотек правильнее указывать в properties, поскольку pom файлы бывают довольно больших размеров и изменение версии может быть не такой простой задачей.

2022-12-05 06:32 UTC, Frilock commented on server/src/main/java/ru/practicum/shareit/item/repository/Item.java
> -    @NotBlank
Валидацию на базе можно было оставить

2022-12-05 06:32 UTC, Frilock commented on server/src/test/java/ru/practicum/shareit/common/aspect/GlobalExceptionHandlerTest.java
> +//class GlobalExceptionHandlerTest {
Ну такое стремно оставлять, давай либо в gateway перенесем либо удалим если не нужен этот функционал больше

2022-12-05 18:00 UTC, Difirton commented on server/src/main/java/ru/practicum/shareit/item/repository/Item.java
> -    @NotBlank
А Вы же сказали полностью удалить зависимость. Поэтому все валидаторы умерли.

2022-12-05 18:01 UTC, Difirton commented on server/src/test/java/ru/practicum/shareit/common/aspect/GlobalExceptionHandlerTest.java
> +//class GlobalExceptionHandlerTest {
Блин, забыл про это. Я его закомментил в самом начале. Так как не давал скомпилироваться проекту. Конечно исправлю.

2022-12-05 20:27 UTC, Difirton commented on server/pom.xml
> +			<version>42.3.8</version>
Я честно попытался... Сделал сначала отдельный модуль с BOM, как в туториале в Bueldung, но он упорно отказывает его находить, мавен  пишет сначала, что все ок, он понимает где какие зависимости, а при компиляции отказался находить BOM. Я тогда решил проще сделать просто в основном pom раздел dependencyManager. Но в докер контейнере, класслоадер почему-то не находит main класс. Хотя локально в идее все запускается. Чуть-чуть полазал, в принципе плагином мавена build это все решается. Но он начал ругаться, что теперь не видит классы спринга. Короче я плюнул и просто вынес версию постгреса вверх=))

2022-12-06 06:44 UTC, Frilock commented on server/pom.xml
> +			<version>42.3.8</version>
Видимо я не совсем корректно выразился, да, я имел ввиду блок dependencyManager в корневом pom. Окей, тут не критично, на дипломе попробуй еще раз, мне кажется гуд практика.

2022-12-06 06:45 UTC, Frilock approved these changes
Ок, принято

2022-12-08 09:08 UTC, merged